title: FFbeast
description: FFBeast documentation
theme: just-the-docs

url: https://ffbeast.github.io

aux_links:
  Discord channel: https://discord.gg/Gt6rnvrZKu
  EMail: mailto:ffbeast.devices@gmail.com

color_scheme: custom
logo: /assets/images/logo.png

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

callouts:
  warning:
    color: red
  highlight:
    color: grey-dk
  note:
    color: green
  important:
    color: blue

plugins:
  - jekyll-redirect-from