title: FFbeast
description: FFBeast documentation
theme: just-the-docs

url: https://ffbeast.github.io

aux_links:
  Github repo: https://github.com/o-devices/bldc-ffb-wheel

color_scheme: custom
logo: /assets/images/logo.jpg